#!/bin/bash
#'Poor mans' shitty gcode plotting 
# (well, if a poor man can see this, he probably could have  downloaded
#  the many  gcode viewers out there)
#
#Note: NOT good, probably doesnt show everything well
#
#Use as pipe; for instance `cat some.gcode | gcode-gnuplot xyn`

ARG=`echo "$@" | cut -s -f 2- -d' '`
echo $ARG
if [ "$ARG" == "" ]; then
    ARG='with dots'
fi

g()
{  grep 'G1 ' | tr X ' ' | tr Y ' ' | tr Z ' '
}
gz()
{  grep G1 | grep Z | tr Z ' '
}

xy()
{   g | gnuplot -p -e "plot '-' using 2:3 $ARG"
}

x()
{   g | gnuplot -p -e "plot '-' using 2 $ARG" 
}

y()
{   g | gnuplot -p -e "plot '-' using 3 $ARG"
}

xyn()
{   g | gnuplot -p -e "splot '-' using 2:3:0 $ARG"
}

z()
{   gz | gnuplot -p -e "plot '-' using 2 $ARG"
}

case $1 in
    xyn)
        xyn ;;
    xy)
        xy ;;
    z)
        z ;;
    x)
        x ;;
    y)
        y ;;
    g)
        g;;
    gz)
        gz ;;
   #TODO e
    *)
        echo "Dont know about plotting $1 about gcodes"  >> /dev/stderr ;;
    
esac
